kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader-mock-ba
subjects:
- kind: ServiceAccount
  name: cluster-reader
  namespace: dsjs
roleRef:
  kind: ClusterRole
  name: read-all
  apiGroup: rbac.authorization.k8s.io
