kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-all
rules:
  - apiGroups: 
      - "*"
    resources:
      - "*"
    verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "watch", "list"]
