apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-reader-secret
  annotations:
    kubernetes.io/service-account.name: cluster-reader
type: kubernetes.io/service-account-token
